### ISSUE TITLE
Slider selection problem

### ISSUE THREAD

**Issue by AdamsTaiwan** [xanderfrangos/twinkle-tray#12]
I just downloaded the latest version from the Windows store. When I select the top slider, the bottom slider moves. When I select the bottom slider, the top slider moves.  Very confusing.
If you want you can see video on my OneDrive
https://1drv.ms/v/s!AjeVI4nhcV5Uk9M_fDjksYlQ2I_XHw

**Comment by xanderfrangos** [comment]
The video link doesn't seem to be working. Could you double check the permissions/link?

**Comment by AdamsTaiwan** [comment]
> The video link doesn't seem to be working. Could you double check the permissions/link?

I changed the link, it should be viewable to anyone with the link.

**Comment by xanderfrangos** [comment]
Thanks, the link is working now. That's definitely not right. I'll see if I can recreate it on my end. It looks like you're using a laptop (or 2-in-1) connected to an external display. Is that right?

**Comment by AdamsTaiwan** [comment]
> Thanks, the link is working now. That's definitely not right. I'll see if I can recreate it on my end. It looks like you're using a laptop (or 2-in-1) connected to an external display. Is that right?

Yes, I'm using a laptop with 2 external monitors.  I'm guess the one monitor is too old to adjust the brightness using software.

**Comment by Leon422** [comment]
Same thing happening to me all of a sudden. 

I'm using a laptop with an external display connected. The external display has DDC enabled and until today I've been able to control the brightness of both my laptop's internal screen and the external screen with no issue. 

However, as of today I can only control the display of the external display. If I try to controll the brightness of the internal laptop display, the slider of the external display moves instead.

My internal display is a Sharp LQ156M1JW03 running at 240 Hz. The external display is an AOC G2590PX monitor, connected via miniDP, running at 144 Hz.

**Comment by xanderfrangos** [comment]
@AdamsTaiwan @Leon422 Good news, I've been able to recreate the problem. I should have a fix ready tomorrow. However, it'll take a few days for the update to roll out to the Windows Store version.

**Comment by Leon422** [comment]
@xanderfrangos Just out of curiosity, was it related to nvidia optimus?

**Comment by xanderfrangos** [comment]
@Leon422 Nope. It's a side-effect from my implementation of the Reorder Monitors feature. There's something wrong with the handling of mixed WMI and DDC/CI setups.

**Comment by xanderfrangos** [comment]
v1.8.2 has been released, fixing this bug. Let me know if you're still seeing any weirdness. The Windows Store version will probably take 1-3 days to roll out. Microsoft is very, very slow.

**Comment by Leon422** [comment]
@xanderfrangos Sooo I installed the regular .exe version of the program and now the brightness sliders works fine but I went to change the sliders for the normalize brightness feature and they won't move. The sliders are stuck on min 0 and max 100 for both monitors. I just can't move them at all.

**Comment by xanderfrangos** [comment]
@Leon422 Are you sure you're on v1.8.2? I just fixed that bug.

**Comment by Leon422** [comment]
@xanderfrangos Yep.
Video: https://streamable.com/w467c

**Comment by xanderfrangos** [comment]
@Leon422 [v1.8.3](https://github.com/xanderfrangos/twinkle-tray/releases) should do the trick.

**Comment by Leon422** [comment]
@xanderfrangos It does, thanks!

**Comment by SteveHe24** [comment]
oops, it still can't work.
![image](https://user-images.githubusercontent.com/78076945/157042474-ba7fe17a-3c67-4eea-ac10-e5500736ebcb.png)
![未命名图片](https://user-images.githubusercontent.com/78076945/157042551-3b3bebbb-8d54-43a7-b3b5-a9fef7833e3c.png)
