### ISSUE TITLE
v1.16.0 beta

### ISSUE THREAD

**Issue by xanderfrangos** [xanderfrangos/twinkle-tray#626]
Hi all,

I have big a new update to Twinkle Tray that I'd love to get some feedback on. There are several new features that have been requested for a long time. I've still got a few things to figure out with the functionality and how it's presented, so the UI/language may change. I'll set up the localization strings once the dust settles.

![Screenshot-2023-07-28-091713](https://github.com/xanderfrangos/twinkle-tray/assets/33106561/9f408532-dc23-4d2f-aaa7-b5c46cdcca9c)

The current release notes are:

> ### New in v1.16.0-beta1
> 
> **New features & improvements:**
> - Added support for user-defined custom DDC/CI features per display. If you supply a valid VCP code (decimal or hexadecimal), a new slider will be added to the brightness flyout.
> - Implemented additional customizations to DDC/CI features (contrast, volume, and custom). You can now set min/max values, and link the feature to the brightness slider. As an example, you could link contrast with brightness, so you can reach lower perceived brightness levels on your monitor than with brightness adjustments alone.
> - Overhauled the hotkeys system. You can now assign multiple monitors per hotkey, set/adjust brightness to any value, and send arbitrary VCP codes (contrast, volume, power state, etc).
> - Implemented per-app brightness profiles. When a specific app is the focused window, a user-defined brightness profile can apply to all displays. The original brightness will be restored when switching back from the app. This should be especially useful for games. Please note that Twinkle Tray does not track which display the app is on. There are no plans for that functionality at this time.
> - Additionally, profiles can be saved to the system tray right-click menu to quickly switch the brightness of multiple monitors to the user-defined profiles.
> - Added option to trigger brightness changes according to the sun's position. Please note that Twinkle Tray cannot get your coordinates. You must provide them yourself.
> - Improved accuracy and details for CLI commands.
> - Twinkle Tray now uses an internal UDP server for certain CLI commands. By default, it will not open ports to your local or external networks. It only communicates over localhost. If you would like to implement a UDP client for external brightness/DDC control, documentation will be available in the future.
> - Changing the power state of a monitor via DDC/CI will now attempt to toggle the display back on, if applicable. You may need to adjust the new "Power State Signal" setting in order for it to work for your monitor(s). Please keep in mind that not all displays correctly support this DDC/CI command and can cause your display to become unresponsive. There is nothing Twinkle Tray can do to further improve compatibility for this DDC/CI command.
> - The code for the Mica blur effect has been refactored to use fewer resources and apply quicker at startup.
> - The amount of brightness changed when using the tray scroll shortcut is now adjustable.
> - Several dependencies have been removed or replaced, reducing the app's size.
> - Hidden displays will no longer be affected by brightness updates.
> 
> **Other information:**
> - The UIs for the new features are not final.
> - Twinkle Tray now reliably builds using the stable Node/Electron versions (as of writing). Additionally, a GitHub Actions CI process has been implemented to monitor successful building. Artifacts from this CI process are not considered stable Twinkle Tray builds. I will not provide any support for builds generated from the CI process. 
> - It is strongly recommended that you use a DDC/CI app such as ControlMyMonitor to understand the capabilities of your display prior to setting up VCP code hotkeys. Twinkly Tray's UI is not designed for quick and arbitrary DDC/CI adjustments outside of brightness control. Twinkle Tray cannot help you if you send a VCP code that makes your display unusable.

The beta is available here:
https://github.com/xanderfrangos/twinkle-tray/releases/tag/v1.16.0-beta8

Let me know if you encounter any new issues vs v1.15.4. Thanks!

**Comment by Spire42** [comment]
When I run v1.16.0 beta, the icon never appears in my notification area, even though there are four Twinkle Tray processes running in the background.

Downgrading to v1.15.4 immediately solves the problem.

I'm on Windows 11 Pro build 22621.2070.

**Comment by xanderfrangos** [comment]
@Spire42 If you don't mind, can you install the latest beta ([v1.16.0-beta2](https://github.com/xanderfrangos/twinkle-tray/releases/tag/v1.16.0-beta2))? If you're still experiencing the issue, can you try manually ending the 4 processes, and then starting Twinkle Tray from the Command Prompt using this command?

`"%LocalAppData%\Programs\twinkle-tray\Twinkle Tray.exe" -console`

Let it run for ~15 seconds and then copy/paste the contents of the console here so I can (hopefully) see what's going on. That would help me greatly.

**Comment by xanderfrangos** [comment]
@sovalyeler Thanks for the bug report and feedback! I've released [v1.16.0-beta2](https://github.com/xanderfrangos/twinkle-tray/releases/tag/v1.16.0-beta2) with a fix for both issues. FYI, you'll need to manually update, as I broke the built-in updater in beta1.

Regarding your two suggestions:
1. If I add anything like that to the profiles, it'll probably be user-defined VCP codes/values (like the hotkeys). 
2. The "Custom Features" UI I have so far is geared towards DDC/CI features like individual color control (RGB), gain, and color temperature. Color presets and input selection definitely don't jive with the slider UI, so I'll probably add an option to switch the current value from a select box (or similar).

**Comment by xanderfrangos** [comment]
@Spire42 I actually just noticed a bug related to upgrading to v1.16.0. If you haven't assigned any hotkeys previously, try adding one in v1.15.4 before upgrading.

**Comment by xanderfrangos** [comment]
@sovalyeler Whoops, I forgot to finish hooking that up. I've fixed the Contrast/Volume hotkey options for the next beta. I'll see about getting multiple actions per hotkey. 👍

**Comment by Spire42** [comment]
> @Spire42 I actually just noticed a bug related to upgrading to v1.16.0. If you haven't assigned any hotkeys previously, try adding one in v1.15.4 before upgrading.

I set up a hotkey and then upgraded to v1.16.0-beta2, and now everything is working. In retrospect, I realize that should have tried upgrading to v1.16.0-beta2 _before_ setting a hotkey to see which one actually fixed the problem.

**Comment by cerahmed** [comment]
I found a few bugs that I'd like to raise:

1) The "Show in right-click tray menu" toggle seems to only show up when "Set Brightness when active" is _enabled_. I'm not sure if that's inteded, but in my case I only need to override the overlay behavior without setting the brightness level.

<img width="496" alt="Screenshot 2023-08-02 085613" src="https://github.com/xanderfrangos/twinkle-tray/assets/21166481/be0faecb-26e5-4b25-83e7-c2783187f3af">
<img width="490" alt="Screenshot 2023-08-02 085658" src="https://github.com/xanderfrangos/twinkle-tray/assets/21166481/9fe3a773-4fa0-4e89-ae1b-fd48fbb872c9">


2) In the example above I sat both monitors to change brightness to 50%, however when activating the profile in the tray menu, the LG monitor goes to 0%! BTW, Display 3 is a TV with no DDC/CI support.

<img width="265" alt="Screenshot 2023-08-02 085750" src="https://github.com/xanderfrangos/twinkle-tray/assets/21166481/d1c9fe1b-0e7c-4ed9-9b7e-4fb0857630be">

3) Profiles do not appear in the right-click tray menu after closing the settings window. I have to quit the app and relaunch it for it to show.

4) I have set the "Override overlay type" to `aggressive`, but that didn't seem to affect anything. The overlay is still blocked by apps like Chrome, VS Code, etc. all in windowed mode.

**Comment by rugabunda** [comment]
> When I run v1.16.0 beta, the icon never appears in my notification area, even though there are four Twinkle Tray processes running in the background.
> 
> Downgrading to v1.15.4 immediately solves the problem.
> 
> I'm on Windows 11 Pro build 22621.2070.

Had the same problem with beta 2, I unisntalled twinkletray using revo uninstaller, cleaned up all the leftover files, reinstalled and the problem was solved, you may not need revouninstaller though; there were very few files left behind

**Comment by xanderfrangos** [comment]
> Installed [v1.16.0-beta4](https://github.com/xanderfrangos/twinkle-tray/releases/tag/v1.16.0-beta4), and now I can't change color presets or contrast by hotkey.

Per the release notes, the hotkeys got reset if you had set them up in a previous v1.16.0 beta. Have you configured them again since upgrading to beta4?

**Comment by xanderfrangos** [comment]
@sovalyeler Whoops, I forgot to update some of the hotkey logic for multiple actions. Give this version a try: https://github.com/xanderfrangos/twinkle-tray/suites/15207469038/artifacts/869087098

**Comment by hacknug** [comment]
In my case every time I open the config screen it shows up empty. Not even the window actions show up and I have to close it from the tray.

**Comment by Kezzers** [comment]
Hi! Just installed Twinkle Tray and I can't open the settings in Beta.
![image_2023-10-03_164410187](https://github.com/xanderfrangos/twinkle-tray/assets/144442715/46ec29bc-34c4-4702-9454-e24ee1a7a262)
This works in the current stable version, but not in Beta.
![image](https://github.com/xanderfrangos/twinkle-tray/assets/144442715/387acd48-4920-4423-9e95-9476d4966bc3)

Would love a fix! I always dim my monitors fully down (+Contrast) and would love that in the settings, as to why I want to use the beta.

**Comment by xanderfrangos** [comment]
Hey, all! I haven't had much time to work on Twinkle Tray lately. When I finally get a chance, I'll take a look at the settings window issue and at least add some debugging so I can determine what's breaking it. I also need to look into hotkeys not working as expected.

**Comment by UsernameIsAlreadyTakenByMe** [comment]
As I know latest beta4 had some issues which was solved by this build: https://github.com/xanderfrangos/twinkle-tray/suites/15207469038/artifacts/869087098 , but this is unavailable now. 
I think I used automatic update and I got the normal beta4 back. Can you share this specific build again, please?

**Comment by xuefer** [comment]
Can't toggle "Link levels" using button in tray icon popup  twinkle-tray-exe-beta-59fe5260a6f952900eded45128a6e789b6cf0947

**Comment by xanderfrangos** [comment]
@xuefer Thanks for the bug report. I'll add that to the list. 👍

**Comment by xuefer** [comment]
unrecognized or delayed for samsung  CS32JG5X Internal name: SAMOFDE
when CS32JG5X is idle or switch off, it act like unplugged, unlike my HKC2400 which stay connected. this cause twinkle-tray to recognize it as unplugged. but when it's back on, while windows recognize it almost immediately (about 1~2 seconds), twinkle may not recognize it or recognized after quite a few seconds, this delay leaves the monitor in wrong brightness since previous set value is not saved across idle or power off. no save means save life for the storage of monitor but it is expected to apply brightness right after monitor is recognized turn on

**Comment by xuefer** [comment]
"CS32JG5X Internal name: SAMOFDE" is unable to put to sleep mode "by windows" when twinkle-tray-exe-beta-59fe5260a6f952900eded45128a6e789b6cf0947 is running
set sleep time 1 minute in windows 10 settings (not twinkle setting), wait 1 minute, all other display go blank then sleep, but CS32JG5X will cycle between blank->sleep->blank (with OSD showing source is "DisplayPort") just can't keep sleeping like other displays

**Comment by xanderfrangos** [comment]
It's taken a lot longer than I intended, but [beta5 is finally out](https://github.com/xanderfrangos/twinkle-tray/releases/tag/v1.16.0-beta5). I've spent a lot of time tinkering with the DDC/CI detection process, since it's technically never been correct. It just happened to work for the majority of users. I'm still not entirely convinced that I have it figured out, but from all of my testing it seems to work fine even under very odd configurations.

I've also fixed a number of things that have been pointed out, along with improving error handling and debugging options. Hopefully those will help get things on track to wrap up v1.16.0.

**Comment by brogers5** [comment]
I'm seeing the following error after updating to beta5:

![Uncaught exception error](https://github.com/xanderfrangos/twinkle-tray/assets/6869577/c947ad6b-dd9a-4f9e-8215-744df3fdc56c)

The tray icon fails to appear after launching, and a few zombie processes will persist until they're manually terminated. The console output is stalling at `Starting Twinkle Tray...`.

**Comment by xanderfrangos** [comment]
@brogers5 Not sure why I can't replicate it, but I know what should fix it. Try this build: https://github.com/xanderfrangos/twinkle-tray/actions/runs/7434125975/artifacts/1151968575

**Comment by brogers5** [comment]
@xanderfrangos Fix confirmed.

**Comment by xanderfrangos** [comment]
I've released beta5.1 with a few fixes. **The built-in updater in beta5 does not work. You need to manually update to beta5.1 [here](https://github.com/xanderfrangos/twinkle-tray/releases/tag/v1.16.0-beta5.1).** Sorry about that!

**Comment by SupDos** [comment]
Beta 5.1 is causing one of my monitors to not be detected consistently, it will sometimes be detected after restarting Twinkle Tray but most of the time it is not detected.

![image](https://github.com/xanderfrangos/twinkle-tray/assets/6813986/3cb83653-def4-46c1-9f58-44ca53d484f2)

![image](https://github.com/xanderfrangos/twinkle-tray/assets/6813986/909d5fdc-7aa6-4f47-a726-ebddcf5791e8)

Beta 4 detects it perfectly fine, and I've tried flipping the new Legacy DDC/CI detection method switch in settings, but it doesn't seem to affect it.

Anything I can do to see why this is happening?

**Comment by xanderfrangos** [comment]
@SupDos Does it show up correctly if you manually refresh? (Right click the tray icon and hit "Refresh displays")

I'll try to put together a quick build today with better logging to help track down the inconsistency.

@sovalyeler This build should work with the 0x14 hotkey: https://github.com/xanderfrangos/twinkle-tray/actions/runs/7439911131/artifacts/1152713722

**Comment by xanderfrangos** [comment]
@SupDos Can you give this build a try with the legacy toggle off? https://github.com/xanderfrangos/twinkle-tray/actions/runs/7441104193/artifacts/1152874767

If it's still not consistently detecting your display, I'd appreciate if you save out a report here in the Debug menu:

![Screenshot 2024-01-07 174026](https://github.com/xanderfrangos/twinkle-tray/assets/33106561/22de6647-091c-427a-b6b3-e760e2f09d43)

A report of when it's detected and another when it's not would be perfect.

**Comment by SupDos** [comment]
@xanderfrangos Manually refreshing doesn't make it show up. Have tried the artifact build you linked, with legacy toggle turned off, and it still doesn't reliably detect the other monitor. 
[tt-report-1704667861966.txt](https://github.com/xanderfrangos/twinkle-tray/files/13855170/tt-report-1704667861966.txt)

**Comment by xanderfrangos** [comment]
@SupDos Thanks for the report! In the Debug menu, can you try setting the "DDC/CI Scanning Mode" to "Fast" or "No validation" and let me know if either of those help?

**Comment by SupDos** [comment]
@xanderfrangos Sadly doesn't seem to help, both of them are inconsistent and will sometimes show the monitor, and other times not

As an example, made a report while using "Fast" - when it detected the monitor, and after refreshing when it lost it, if it helps at all

[tt-report-1704669845259-fast-detected.txt](https://github.com/xanderfrangos/twinkle-tray/files/13855255/tt-report-1704669845259-fast-detected.txt)
[tt-report-1704669867576-fast-notdetected.txt](https://github.com/xanderfrangos/twinkle-tray/files/13855256/tt-report-1704669867576-fast-notdetected.txt)

**Comment by xanderfrangos** [comment]
@SupDos That helps quite a bit. 👍 Can you try this build with the "Fast" setting? https://github.com/xanderfrangos/twinkle-tray/actions/runs/7441444611/artifacts/1152919705

**Comment by SupDos** [comment]
Still inconsistent with that build unfortunately. On first install it didn't detect it, relaunching it made it detect it, next relaunch it detected it again, after that it no longer seems to be detecting it - all on "Fast" without changing any options in between launches

**Comment by xanderfrangos** [comment]
@SupDos Hmm, okay. Do you mind uploading another report from when it's not working?

**Comment by SupDos** [comment]
@xanderfrangos No validation doesn't seem to be different. On both of them it will sometimes be detected, but then after refreshing monjtors or restarting Twinkle Tray it will vanish
[tt-report-1704672688998-noval.txt](https://github.com/xanderfrangos/twinkle-tray/files/13855404/tt-report-1704672688998-noval.txt)
[tt-report-1704672819158-fast.txt](https://github.com/xanderfrangos/twinkle-tray/files/13855405/tt-report-1704672819158-fast.txt)
Both of these are when the monitor is not being detected.

**Comment by xanderfrangos** [comment]
@SupDos Those reports help, thanks. I need to tweak the report to get a little more info that's not showing up reliably from your monitors. I'll send over a new build soon. I appreciate your help debugging this!

**Comment by xanderfrangos** [comment]
@SupDos Can you upload a report from when the monitor is _not_ detected, using this build? Either the "Fast" or "No validation" option is fine. https://github.com/xanderfrangos/twinkle-tray/actions/runs/7441952831/artifacts/1152992313

**Comment by xanderfrangos** [comment]
After a bit of research, I have a reasonable level of confidence that I've fixed the issue in this build: https://github.com/xanderfrangos/twinkle-tray/actions/runs/7443105855/artifacts/1153165662

**Comment by SupDos** [comment]
@xanderfrangos sorry for not getting back till now, the last build you posted seems to have fixed it! Have restarted/refreshed multiple times and both monitors appear! What Scanning Mode should I leave it in? I've tried Accurate, Fast and No Validation and they all work perfectly fine

**Comment by xanderfrangos** [comment]
@SupDos Great! Hopefully that's the only hiccup with the new DDC/CI code, but we'll see. I'll roll out a new beta version with this fix for more people to test. You should set the "Scanning Mode" to "Accurate". Thanks again for the help debugging/testing. 👍

**Comment by xanderfrangos** [comment]
I've released [beta5.2](https://github.com/xanderfrangos/twinkle-tray/releases/tag/v1.16.0-beta5.2) with the hotkey/monitor fixes. (Nothing new since the build a few comments up.)

**Comment by Atlantis-Gura** [comment]
@xanderfrangos Hi, I'm using the latest build v1.16.0-beta5.2 and found that the "Animate Between Times" function is not working as expected, as stated in Issue #661 . For example, in my case today, between Sunrise (08:04) brightness 22 and Solar Noon (12:12) brightness 36, I turned on "Animate Between Times", so I got a brightness of 30 at about 09:00, 28 at 10:00, and 27 at 10:30, which doesn't make sense. I honestly don't know the original intent of this feature, but I think it's supposed to create a smooth curve between two time points, during which the brightness is allowed to smoothly go up/down based on time. 

I think one of the important features that v1.16 brings to users is the ability to set the change in brightness according to the position of the sun. So, if these two functions can be combined, then automated adjustment of brightness will become very convenient. I would appreciate it if you could take the time to check what the problem is.

**Comment by xanderfrangos** [comment]
@Atlantis-Gura You're correct that it should be a smooth transition between two times. Can you share your settings file, so I can try to recreate the issue? You can quickly get it from the "Debug" menu, found in the bottom left of the settings window.

**Comment by xuefer** [comment]
> "CS32JG5X Internal name: SAMOFDE" is unable to put to sleep mode "by windows" when twinkle-tray-exe-beta-59fe5260a6f952900eded45128a6e789b6cf0947 is running set sleep time 1 minute in windows 10 settings (not twinkle setting), wait 1 minute, all other display go blank then sleep, but CS32JG5X will cycle between blank->sleep->blank (with OSD showing source is "DisplayPort") just can't stay in sleeping mode like other displays

still reproduced with beta v1.16.0-beta5.2

**Comment by xuefer** [comment]
> unrecognized or delayed for samsung CS32JG5X Internal name: SAMOFDE when CS32JG5X is idle or switch off, it act like unplugged, unlike my HKC2400 which stay connected. this cause twinkle-tray to recognize it as unplugged. but when it's back on, while windows recognize it almost immediately (about 1~2 seconds), twinkle may not recognize it or recognized after quite a few seconds, this delay leaves the monitor in wrong brightness since previous set value is not saved across idle or power off. no save means save life for the storage of monitor but it is expected to apply brightness right after monitor is recognized turn on
> 
> When it's unrecognized, adjusting brightness won't apply it to monitor, yet the monitor is listed in "Monitor Settings" page. "refresh displays" is needed to get out of this buggy state.

still reproduced with beta v1.16.0-beta5.2. have to refresh display every time

**Comment by xanderfrangos** [comment]
@xuefer It may be detected by Windows and Twinkle Tray, but not be ready for DDC/CI. Try increasing the "Hardware change time" in the debug menu:

![Screenshot 2024-01-09 113759](https://github.com/xanderfrangos/twinkle-tray/assets/33106561/66b09c2b-3558-42ec-bb09-f595acebe018)

Set it to something like 15 seconds as a test. Then after unplugging/plugging it in again, see if it works correctly after around 20 seconds. If that helps, you can try lowering the time until it stops working again and go back up a few numbers.

Let me know if that helps.

**Comment by xuefer** [comment]
> @xuefer It may be detected by Windows and Twinkle Tray, but not be ready for DDC/CI. Try increasing the "Hardware change time" in the debug menu:
> Set it to something like 15 seconds as a test. Then after unplugging/plugging it in again, see if it works correctly after around 20 seconds. If that helps, you can try lowering the time until it stops working again and go back up a few numbers.
> 
> Let me know if that helps.

nope. waking up from "turn off display", still reproduce the issue with 15 seconds. but manual refresh immediately after wake up make brightness ok

**Comment by Atlantis-Gura** [comment]
> @Atlantis-Gura You're correct that it should be a smooth transition between two times. Can you share your settings file, so I can try to recreate the issue? You can quickly get it from the "Debug" menu, found in the bottom left of the settings window.

@xanderfrangos Sure. [settings.json](https://github.com/xanderfrangos/twinkle-tray/files/13877637/settings.json)

After my further testing, the transition between the two times seems to be the opposite of what was expected: from time A (brightness set to 40) to time B (brightness set to 60), the brightness should have transitioned from 40 to 60, but now the brightness is from 60 to 40. This situation is still the same even if the sun position is not used.

**Comment by xanderfrangos** [comment]
@xuefer If you don't mind, could you generate a report for me before and after the manual refresh? You can find the report button here:
![Screenshot 2024-01-07 174026](https://github.com/xanderfrangos/twinkle-tray/assets/33106561/22de6647-091c-427a-b6b3-e760e2f09d43)

@Atlantis-Gura Thanks! The settings and detailed info help. There's definitely something wrong with the math. I'll look into it.

**Comment by xanderfrangos** [comment]
@Atlantis-Gura The calculations should be fixed in this build: https://github.com/xanderfrangos/twinkle-tray/actions/runs/7466557973/artifacts/1157848291

**Comment by Atlantis-Gura** [comment]
@xanderfrangos After a simple test now the problem seems to be solved and the transition between the two times works fine. Thanks for your help!

**Comment by xuefer** [comment]
> @xuefer If you don't mind, could you generate a report for me before and after the manual refresh? 

[1-before.txt](https://github.com/xanderfrangos/twinkle-tray/files/13883195/1-before.txt)
[2-after.txt](https://github.com/xanderfrangos/twinkle-tray/files/13883196/2-after.txt)

**Comment by hacknug** [comment]
I can confirm that with v1.16.0-beta5.2 the Settings window works as it used to and it doesn't show up empty anymore. Fix was implemented in v1.16.0-beta5 but I didn't update until now.

**Comment by xanderfrangos** [comment]
@xuefer Weird. Can you give this build a try and let me know if it helps? It refreshes twice after a hardware change. So in theory it should be doing what you've been doing manually, automatically.

https://github.com/xanderfrangos/twinkle-tray/actions/runs/7493620770/artifacts/1163423754

**Comment by xuefer** [comment]
> @xuefer Weird. Can you give this build a try and let me know if it helps? It refreshes twice after a hardware change. So in theory it should be doing what you've been doing manually, automatically.
> 
> https://github.com/xanderfrangos/twinkle-tray/actions/runs/7493620770/artifacts/1163423754

not helping.

but it seems i have found the problem. never detect hardware change. when i unplug/plug another monitor, devmgmt.msc refresh itself, but twinkle-tray does not refresh(remove or add) the monitor. is there anything I should check? "Shell Hardware Detection" service is running, not disabled

**Comment by xanderfrangos** [comment]
@xuefer Interesting. I've added a different method for detecting hardware changes in this build. In theory, it should fix the issue: https://github.com/xanderfrangos/twinkle-tray/actions/runs/7514246889/artifacts/1167454272

**Comment by xuefer** [comment]
this one is ok.

btw, 2 seconds delay works for both of my external screens

**Comment by zhouym233** [comment]
![image](https://github.com/xanderfrangos/twinkle-tray/assets/26868483/532a596a-d612-42fb-a17a-19a9faefb11c)
It does not works in v1.16.0-beta5.3(e25b507)。But when I switch "DDC/CI Scanning Mode" to "No validation", it works.
[tt-report-1706536933295.txt](https://github.com/xanderfrangos/twinkle-tray/files/14085154/tt-report-1706536933295.txt)

**Comment by xanderfrangos** [comment]
@zhouym233 Thanks for providing the report. 👍

Does it work if you set "DDC/CI Scanning Mode" to "Fast" or "Legacy"?

**Comment by xanderfrangos** [comment]
Also, can you share a report from when it's working (using "No validation")?

**Comment by zhouym233** [comment]
It works  in "Legacy"  and "Fast"  mode too. but after I changed the options a few times, it probably doesn't work again . "Accurate" mode never works.
[tt-report-1706549740931-noValidation.txt](https://github.com/xanderfrangos/twinkle-tray/files/14087734/tt-report-1706549740931-noValidation.txt)
[tt-report-1706549827950-legacy.txt](https://github.com/xanderfrangos/twinkle-tray/files/14087735/tt-report-1706549827950-legacy.txt)
[tt-report-1706550384096-fast.txt](https://github.com/xanderfrangos/twinkle-tray/files/14087786/tt-report-1706550384096-fast.txt)

**Comment by xanderfrangos** [comment]
Interesting, thanks for confirming all of that. Have you used an earlier version of Twinkle Tray (like v1.15.4) before without issue?

**Comment by zhouym233** [comment]
> Interesting, thanks for confirming all of that. Have you used an earlier version of Twinkle Tray (like v1.15.4) before without issue?

Yes, v1.15.4 works , but occasionally it had some issues with hotkeys, so I updated to the beta version.

**Comment by shafayetejaman** [comment]
Unlike the windows volume adjustment bar, the twinkle tray scrolling bar for the systray and taskbar popup has no exciting animation.
It would be more consistent with windows 11 design if the twinkle tray had an exiting animation.

**Comment by xanderfrangos** [comment]
> Unlike the windows volume adjustment bar, the twinkle tray scrolling bar for the systray and taskbar popup has no exciting animation.
> It would be more consistent with windows 11 design if the twinkle tray had an exiting animation.

Older versions of Twinkle Tray had exit animations, but due to the tray flyout and hotkey flyout sharing the same renderer, it was too much trouble to maintain. Maybe one day I'll give it another try, but I have to finally get v1.16.0 out the door before I work on something like that. It's not a high priority. I appreciate the suggestion though.

**Comment by Dragonisser** [comment]
Any news when it will come?

**Comment by shafayetejaman** [comment]
After Windows auto turns off the display feature executes and the display turns off itself, the brightness level does not retain the last set level.

**Comment by jessicah** [comment]
Upgraded from v1.15.5 to v1.16.0-beta7, and getting a weird javascript error trying to toggle power from the system tray. When trying to use a keyboard shortcut, nothing happens either, I guess because of this error.

```
[Content]
Uncaught Exception:
TypeError: Cannot set properties of undefined (setting '0xD6')
    at EventEmitter.<anonymous> (C:\Users\jessi\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:203:45)
    at Object.onceWrapper (node:events:634:26)
    at EventEmitter.emit (node:events:519:28)
    at ChildProcess.<anonymous> (C:\Users\jessi\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:186:28)
    at ChildProcess.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by xanderfrangos** [comment]
> Upgraded from v1.15.5 to v1.16.0-beta7, and getting a weird javascript error trying to toggle power from the system tray. When trying to use a keyboard shortcut, nothing happens either, I guess because of this error.
> 
> ```
> [Content]
> Uncaught Exception:
> TypeError: Cannot set properties of undefined (setting '0xD6')
>     at EventEmitter.<anonymous> (C:\Users\jessi\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:203:45)
>     at Object.onceWrapper (node:events:634:26)
>     at EventEmitter.emit (node:events:519:28)
>     at ChildProcess.<anonymous> (C:\Users\jessi\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:186:28)
>     at ChildProcess.emit (node:events:519:28)
>     at emit (node:internal/child_process:951:14)
>     at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
> ```
> 
> Hmm, not a particularly useful stack trace from the popup window either. Unfortunately, nothing in the console when running a local build either :-/

Fixed in [beta8](https://github.com/xanderfrangos/twinkle-tray/releases/tag/v1.16.0-beta8), amongst other fixes. Thanks for pointing it out. 👍

**Comment by xanderfrangos** [comment]
I've moved everything to the `master` branch and plan to roll out a formal release Soon™️. Hopefully beta8 has fixed most of the outstanding issues introduced in earlier beta versions. 😅

**Comment by jessicah** [comment]
> > Upgraded from v1.15.5 to v1.16.0-beta7, and getting a weird javascript error trying to toggle power from the system tray. When trying to use a keyboard shortcut, nothing happens either, I guess because of this error.
> > ```
> > [Content]
> > Uncaught Exception:
> > TypeError: Cannot set properties of undefined (setting '0xD6')
> >     at EventEmitter.<anonymous> (C:\Users\jessi\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:203:45)
> >     at Object.onceWrapper (node:events:634:26)
> >     at EventEmitter.emit (node:events:519:28)
> >     at ChildProcess.<anonymous> (C:\Users\jessi\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:186:28)
> >     at ChildProcess.emit (node:events:519:28)
> >     at emit (node:internal/child_process:951:14)
> >     at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hmm, not a particularly useful stack trace from the popup window either. Unfortunately, nothing in the console when running a local build either :-/
> 
> Fixed in [beta8](https://github.com/xanderfrangos/twinkle-tray/releases/tag/v1.16.0-beta8), amongst other fixes. Thanks for pointing it out. 👍

Ah, that works, but! if I try setting up a hotkey to cycle values for `D6` (1 & 4), this doesn't work :-/ Other hotkeys work. And a hotkey for the builtin action "Turn off displays" works. But that one doesn't allow turning them back on...

**Comment by shafayetejaman** [comment]
[BUG!] In beta8 systray icon not showing after going to sleep bug it is running in the background. Keyboard shortcuts still work without the systray icon.

**Comment by xanderfrangos** [comment]
v1.16.0 has been released! I've cleaned up a small number of bugs since beta8 (which _should_ include the above issue). Please let me know if you're still experiencing issues with the system tray icon. 

I'm closing this issue, as there's no longer a "beta". Thank you, everyone, for helping test this long overdue update!

**Comment by Dragonisser** [comment]
When will this version arrive in the Windows Store?

**Comment by xanderfrangos** [comment]
@Dragonisser "Soon™"

I'm still fixing a few issues that have been reported. If nothing new comes up with v1.16.3, that'll hopefully be the release that gets to the MS Store. If you want it sooner, I recommend uninstalling the MS Store version and switching to the version from GitHub.
